Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TaskManager.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Pages/Index.cshtml.cs
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.Json.Nodes;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using TaskManager.Model;


namespace TaskManager.Pages
{

    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IConfiguration _config;

        [BindProperty]
        public string selectedFilter { get; set; }

        [BindProperty]
        public int Priority { get; set; }

        [BindProperty]
        public string Status { get; set; }

        [BindProperty]
        public int Priorityval { get; set; }

        [BindProperty]
        public string Statusval { get; set; }


        [BindProperty]
        public string TaskName { get; set; }

        [BindProperty]
        public int Selectedpriority { get; set; }

        [BindProperty]
        public string Selectedstatus { get; set; }



        public List<Model.Tasks> tasklist = new List<Model.Tasks>();

        public string ActionResultMessageText { get; set; }

        public int ActionResultPriorityText { get; set; }
        public string ActionResultErrorMessageText { get; set; }

        public IndexModel(ILogger<IndexModel> logger, IConfiguration config)
        {
            _logger = logger;
            _config = config;
        }


        public void OnGet()
        {

            Fetchdata();

        }
        [HttpPost]
        public void OnPost()
        {

            Fetchdata();

        }
        public async void OnGetSearch()
        {

            Fetchdata();

        }
        /// <summary>
        /// Update Priority ans status based on Taskname
        /// </summary>
        /// <returns></returns>

        public async Task<IActionResult> OnPostEditdata()
        {



            Tasks task = new Tasks();
            task.Name = TaskName;
            task.Priority = Priorityval;
            task.Status = Statusval;


            TaskItem objtask = new(_config);

            var response = objtask.UpdateTask(task);
            if (response == "update failed")
            {




            }
            else
            {

                Fetchdata();

            }


            return RedirectToPage("./Index");


            //Tasks objtask = new Tasks();
            //objtask.Name = TaskName;
            //objtask.Priority = Priorityval;
            //objtask.Status = Statusval;

            //var jsonContent = JsonConvert.SerializeObject(objtask);
            //var contentData = new StringContent(jsonContent, Encoding.UTF8, "application/json");

            //var url = _config.GetSection("Apiurl").Value;

            //using (var client = new HttpClient())
            //{

            //    var HttpResponseMessage = await client.PutAsync(url + "api/Task", contentData);

            //    Fetchdata();


            //}
            //return RedirectToPage("./Index");



        }
        /// <summary>
        /// Delete data based on name
        /// </summary>
        /// <returns></returns>

        public async Task<IActionResult> OnPostDeletedata()
        {
            Tasks objtask = new Tasks();
            objtask.Name = TaskName;
            objtask.Priority = Priority;
            objtask.Status = Status;

            var jsonContent = JsonConvert.SerializeObject(objtask);
            var contentData = new StringContent(jsonContent, Encoding.UTF8, "application/json");

            var url = _config.GetSection("Apiurl").Value;

            using (var client = new HttpClient())
            {

                var HttpResponseMessage = await client.DeleteAsync(url + "api/Task/" + objtask.Name);               
                Fetchdata();


            }
            return RedirectToPage("./Index");


        }

        /// <summary>
        /// Opens the popup page for edit/delete
        /// </summary>
        /// <param name="LogId"></param>
        public void OnPostUpdatedata(string LogId)
        {
            Fetchdata();

            var url = _config.GetSection("Apiurl").Value;
            this.ActionResultMessageText = string.Empty;
            this.ActionResultErrorMessageText = LogId;

            if (RouteData.Values["LogId"] != null)
            {
                string LogId1 = (RouteData.Values["LogId"].ToString());

            }

            var tsk = tasklist.Where(u => u.Name == LogId).FirstOrDefault();
            TaskName = tsk.Name;
            Priorityval = tsk.Priority;
            Statusval = tsk.Status;





        }
        /// <summary>
        /// Search and load grid based on priority and status
        /// </summary>

        //  public async Task<IActionResult> OnPostSearchdata()
        public async void OnPostSearchdata()
        {
            var url = _config.GetSection("Apiurl").Value;

            using (var client = new HttpClient())
            {
                HttpRequestMessage request = new HttpRequestMessage();
                request.RequestUri = new Uri(url + "api/Task");
                request.Method = HttpMethod.Get;
                HttpResponseMessage res = client.Send(request);
                var responseStr = res.Content.ReadAsStringAsync();
               

                this.tasklist = JsonConvert.DeserializeObject<List<Tasks>>(responseStr.Result);

                if (Selectedpriority > 0) { this.tasklist = this.tasklist.Where(u => u.Priority == Selectedpriority).ToList(); }
                if (!string.IsNullOrEmpty(Selectedstatus)) { this.tasklist = this.tasklist.Where(u => u.Status == Selectedstatus).ToList(); }

               

            }
            
        }


        /// <summary>
        /// Call to the get APi method
        /// </summary>


        public void Fetchdata()
        {
            var url = _config.GetSection("Apiurl").Value;
            using (var client = new HttpClient())
            {
                HttpRequestMessage request = new HttpRequestMessage();
                request.RequestUri = new Uri(url + "api/Task");
                request.Method = HttpMethod.Get;
                HttpResponseMessage res = client.Send(request);
                var responseStr = res.Content.ReadAsStringAsync();
                //tasklist = JsonConvert.DeserializeObject<List<Model.Tasks>>(responseStr.Result);

                tasklist = JsonConvert.DeserializeObject<List<Tasks>>(responseStr.Result);
                if (Priority > 0) { tasklist = tasklist.Where(u => u.Priority == Priority).ToList(); }
                if (!string.IsNullOrEmpty(Status)) { tasklist = tasklist.Where(u => u.Status == Status).ToList(); }


              ;
                var statusCode = res.StatusCode;
                
            }
        }

        public void OnPostopenpopup()
        {
            this.ActionResultMessageText = string.Empty;
            this.ActionResultErrorMessageText = "Success";

        }


    }

}

Pages/ViewTaskDetails.cshtml.cs
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using TaskManager.Model;

namespace TaskManager.Pages
{
    public class ViewTaskDetailsModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IConfiguration _config;

        [BindProperty]
        public string TaskName { get; set; }

        [BindProperty]
        public int Priority { get; set; }

        [BindProperty]
        public string Status { get; set; }

        public List<Model.Tasks> tasklist = new List<Model.Tasks>();

        public string ActionResultMessageText { get; set; }
        public string ActionResultErrorMessageText { get; set; }

        public ViewTaskDetailsModel(ILogger<IndexModel> logger, IConfiguration config)
        {
            _logger = logger;
            _config = config;
        }

        public async void OnGet()
        {
            var url = _config.GetSection("Apiurl").Value;
            using (var client = new HttpClient())
            {
                HttpRequestMessage request = new HttpRequestMessage();
                request.RequestUri = new Uri(url + "api/Task");
                request.Method = HttpMethod.Get;
                HttpResponseMessage res = client.Send(request);
                var responseStr = await res.Content.ReadAsStringAsync();
                List<Tasks> task = JsonConvert.DeserializeObject<List<Tasks>>(responseStr);
                var statusCode = res.StatusCode;

            }

        }

        public async void OnPostOnSave()
        {
            Tasks objtask = new Tasks();
            objtask.Name = TaskName;
            objtask.Priority = Priority;
            objtask.Status = Status;

            bool bval = Fetchdata(objtask.Name);
            if (bval == false)
            {
                this.ActionResultMessageText = string.Empty;
                this.ActionResultErrorMessageText = "Record already exists";
            }
            else
            {
                this.ActionResultMessageText = string.Empty;
                var jsonContent = JsonConvert.SerializeObject(objtask);
                var contentData = new StringContent(jsonContent, Encoding.UTF8, "application/json");

                var url = _config.GetSection("Apiurl").Value;
                var _httpClient = new HttpClient();

                // Send the POST request
                HttpResponseMessage response = await _httpClient.PostAsync(url + "api/Task", contentData);

                // Read and display the response
                string responseString = await response.Content.ReadAsStringAsync();
                if (response.IsSuccessStatusCode)
                {

                    this.ActionResultErrorMessageText = "Record  Created";
                }
            }


        }


        public async Task OnPostCreatedata()
        {


            TaskItem task = new TaskItem(_config);


            Tasks objtask = new Tasks();
            objtask.Name = TaskName;
            objtask.Priority = Priority;
            objtask.Status = Status;


            bool bval = Fetchdata(objtask.Name);
            if (bval == false)
            {
                this.ActionResultMessageText = string.Empty;
                this.ActionResultErrorMessageText = "Record already exists";
            }
            else
            {

                var response = await task.CreateTask(objtask);



                this.ActionResultMessageText = string.Empty;
                this.ActionResultErrorMessageText = response;




                //this.ActionResultMessageText = string.Empty;
                //var jsonContent = JsonConvert.SerializeObject(objtask);
                //var contentData = new StringContent(jsonContent, Encoding.UTF8, "application/json");

                //var url = _config.GetSection("Apiurl").Value;
                //var _httpClient = new HttpClient();

                //// Send the POST request
                //HttpResponseMessage response = await _httpClient.PostAsync(url + "api/Task", contentData);

                //// Read and display the response
                //string responseString = await response.Content.ReadAsStringAsync();

                //if (response.IsSuccessStatusCode)
                //{
                //    this.ActionResultMessageText = string.Empty;
                //    this.ActionResultErrorMessageText = "Record created";

                //}

            }




        }
        public void OnpostModel(string name)
        {
            ViewData["Message"] = "Added";
        }
        public async void OnPostopenpopup()
        {
            this.ActionResultMessageText = string.Empty;
            this.ActionResultErrorMessageText = "Success";

        }

        public bool Fetchdata(string Name)
        {
            var url = _config.GetSection("Apiurl").Value;
            using (var client = new HttpClient())
            {
                HttpRequestMessage request = new HttpRequestMessage();
                request.RequestUri = new Uri(url + "api/Task");
                request.Method = HttpMethod.Get;
                HttpResponseMessage res = client.Send(request);
                var responseStr = res.Content.ReadAsStringAsync();
                
                //tasklist = JsonConvert.DeserializeObject<List<Model.Tasks>>(responseStr.Result);

                tasklist = JsonConvert.DeserializeObject<List<Tasks>>(responseStr.Result);
                var TaskName = tasklist.Where(u => u.Name == Name).FirstOrDefault();
                if (TaskName == null)

                {
                    return true;
                }
                else
                {

                    return false;
                }
            }
        }


    }
}

Pages/Index.cshtml
@page
@* @using TaskManager.Model *@
  @model IndexModel


@{
    ViewData["Title"] = "";
    
}
<h1>@ViewData["Title"]</h1>

<html>
<head>
    <style>
        select#Status {
            max-width:100px;
            min-width: 100px;
            width: 100px !important;
        }
    </style>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/css/mvc-grid/mvc-grid.css" rel="stylesheet" />
</head>
<body style="background-color:lightgray">
    <form action="" method="post" name="registration" class="register form-horizontal" >
         <div class="col-sm-6" >
        @* <div class="modal fade" id="myModal"> *@
            <label for="Prioritylabel" class="col-sm-2 control-label">Priority: </label>
            @* <input name="Priority" class="form-control" asp-for="Priority"> *@
            <select name="Priority" id="Priority" asp-for="Priority" class="dropdown" style="min-width:50px;" >
                <option value=""></option>
                <option value=1>1</option>
                <option value=2>2</option>
                <option value=3>3</option>
                <option value=4>4</option>
                <option value=5>5</option>
                <option value=6>6</option>

            </select>

            <label for="Status" class="col-sm-2 control-label">Status: </label>
            <select name="Status" id="Status" asp-for="Status" class="dropdown">
                <option value=""></option>
                <option value="Yet to Complete">Yet to Complete</option>
                <option value="in Progress">in Progress</option>
                <option value="Completed">Completed</option>
            </select>
            <form method="post">
                <input asp-page-handler="Searchdata" id="Search" class="Search" type="submit" value="Search" />
                <input type="hidden" name="Selectedpriority" id="Selectedpriority" value="" />
                <input type="hidden" name="Selectedstatus" id="Selectedstatus" value="" />
            </form>
    </div>
   
    <div>

        </div>
        <br />
        <table class="table" border="1" style="border-width:2px;border-block-color:black;">
       
        <thead>

            <tr>
                <th>Task Name</th>
                <th>Priority</th>
                <th>Status</th> 
                <th></th>
            </tr>
        </thead>
        <tbody >
           @foreach (var tasklist in Model.tasklist.ToList())
            {
                    if (@tasklist.Priority>0)
                    {
                        <tr>
                            <td> @tasklist.Name  </td>
                            <td>@tasklist.Priority</td>
                            <td>@tasklist.Status</td>
                            <td>
                                <form asp-route-LogId="@tasklist.Name" asp-page-handler="Updatedata">
                                    <button class="btn btn-info" name="Edit/Delete">Edit/Delete</button>
                                    <input type="hidden" name="LogId" value="@tasklist.Name" />
                                </form>
                            </td>
                        </tr>
                    }
               
            }            
            
        </tbody>
    </table>        
    </form>
    <div>
      
    </div>
    <form action="" method="post" name="registration" class="register form-horizontal">
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Task Details</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
            
                <div class="form-group">
                        <label for="Name" class="col-sm-2 control-label">Name:</label>
                      
                            <input type="text" name="TaskName" asp-for="TaskName" readonly="true"  />
                   
                    </div>
                
            
                    <div class="form-group">
                        <label for="Status" class="col-sm-2 control-label">Status:</label>
                    <select id="Statusval" name="Statusval" asp-for="Statusval">
                        <option value=""></option>
                        <option value="Yet to Complete">Yet to Complete</option>
                        <option value="in Progress">in Progress</option>
                        <option value="Completed">Completed</option>
                    </select>
                </div>
                    <div class="form-group">
                        <label for="Priority" class="col-sm-2 control-label">Priority:</label>
                    <select name="Priorityval" asp-for="Priorityval">
                        <option value=""></option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                    </select>
                </div>
                <div class="modal-footer">
                   
                     <button class="btn btn-info" name="regbutton" value="Create" data-pdsa-action="Save" asp-page-handler="Editdata">Submit</button>
                        <button class="btn btn-info" name="delete" value="Create"  asp-page-handler="Deletedata" onclick="Validatedelete()">Delete</button>
                </div>
            </div>
        </div>
    </div>
    </form>
    
</body>
</html>
@if (Model.ActionResultMessageText == string.Empty)
{
    <script type="text/javascript">
       
        window.onload = function () {
            $("#exampleModal").modal("show")
        };



       

    </script>
}
@section Scripts
{
    <script type="text/javascript">
     
       
                  $("#Priority").on("change", function () {
                     
                      var selectedValue  = $(this).val();                   
                       $('#Selectedpriority').val(selectedValue);   
        });
                  

                      $("#Status").on("change", function () {                      
                      var selectedValue  = $(this).val();                     ;
                       $('#Selectedstatus').val(selectedValue); 
        });


        function Validatedelete()
        {

           var Status=document.getElementById("Statusval").value;
          
           if(Status!="Completed")
           {
               alert("Completed Status allowed only for deletion ");
               event.preventDefault();
               return false;
           }

        }

 
                

    </script>

}

Pages/ViewTaskDetails.cshtml
@page
@* @using TaskManager.Model *@
 @model ViewTaskDetailsModel
@* @model Tasks *@

@{
    ViewData["Title"] = "Home page";

}

<html>
<head>

</head>
<body>

    <form action="" method="post" name="registration" class="register form-horizontal" style="background-color:lightgray">
        <fieldset>
            <legend></legend>

            <div class="form-group">
                <label for="Name" class="col-sm-2 control-label">Name:</label>
                <div class="col-sm-6" style="width:250px;">
                    <input name="TaskName" id="name" class=" form-control" asp-for="TaskName">
                </div>
            </div>
            <br />

            <div class="form-group">
                <label for="Priority" class="col-sm-2 control-label">Priority: </label>
                <div class="col-sm-6">
                    <select name="Priority" id="Priority" asp-for="Priority" class="dropdown" style="min-width:130px">
                        <option value="">""</option>
                        <option value=1>1</option>
                        <option value=2>2</option>
                        <option value=3>3</option>
                        <option value=4>4</option>
                        <option value=5>5</option>
                        <option value=6>6</option>
                    </select>
                </div>
            </div>
            <br />
            <div class="form-group">
                <label for="Status" class="col-sm-2 control-label">Status: </label>
                <div class="col-sm-6">

                    <div class="col-sm-6">
                        <select name="Status" id="Status" asp-for="Status" style="min-width:50px;">
                            <option value="">""</option>
                            <option value="Yet to Complete">Yet to Complete</option>
                            <option value="in Progress">in Progress</option>
                            <option value="Completed">Completed</option>
                        </select>
                    </div>
                </div>
            </div>
            <br />

            <button class="btn btn-info" name="regbutton" value="Create" data-pdsa-action="Save" asp-page-handler="Createdata" onclick="Validatedata()">Submit</button>

     
         
        </fieldset>
    </form>
   
    <form action="" method="post" name="registration" class="register form-horizontal">
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Task Details</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        @Model.ActionResultErrorMessageText
                    </div>
                </div>
            </div>
        </div>
    </form>
</body>
</html>



@if (Model.ActionResultErrorMessageText != null)
{
    <script type="text/javascript">

        window.onload = function () {
              $("#exampleModal").modal("show")

          };

    </script>
}


<script type="text/javascript">
    function Validatedata()
    {

       var Status=document.getElementById("Status").value;
       var Priority=document.getElementById("Priority").value;
       var TaskName=document.getElementById("name").value;
      

       if(Status=="" || Priority==0 || TaskName==null )
       {
           alert("Values are empty");
           event.preventDefault();
           return false;
       }
       if(Status=="Completed")
       {
           alert("Completed Status not allowed in Task Creation");
           event.preventDefault();
           return false;
       }

    }

</script>